substitutions:
  _AR_REGION: "asia-southeast1"
  _AR_REPO: "app-repo"
  _IMAGE_NAME: "asb-ml-app"

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA','.']

  - name: gcr.io/cloud-builders/docker
    args: ['push','${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      ['run','deploy','${_IMAGE_NAME}',
       '--image','${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA',
       '--region','asia-southeast1','--platform','managed','--allow-unauthenticated',
       '--memory','2Gi','--cpu','2','--timeout','600','--concurrency','5']
options:
  logging: CLOUD_LOGGING_ONLY
