substitutions:
  _AR_REGION: "asia-southeast1"
  _AR_REPO: "app-repo"
  _IMAGE_NAME: "asb-ml-app"
  _SERVICE_NAME: "asb-ml-app"
steps:
# Step 1: Docker Build
# If your Dockerfile needs GEMINI_API_KEY during the build phase (e.g., as a build-arg),
# you would uncomment the 'env' block and potentially modify 'args' here.
# Otherwise, no 'env' block is needed for 'docker build' if the key is only for runtime.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/ecgcga/app-repo/asb-ml-app:3f3c1fa', '.']
  # Example if Dockerfile uses ARG GEMINI_API_KEY:
  # env:
  # - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
  # args: ['build', '--build-arg', 'GEMINI_API_KEY=${_GEMINI_API_KEY}', '-t', '...', '.']

# Step 2: Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/ecgcga/app-repo/asb-ml-app:3f3c1fa']

# Step 3: Deploy to Cloud Run (This is where the secret is used)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # The GEMINI_API_KEY environment variable is now available in this shell
    # because it's explicitly set in the 'env' block below for *this* step.
    # When passing it as an environment variable to Cloud Run, use the double dollar sign ($$)
    # to ensure the shell passes the *value* of the variable to the gcloud command.
    gcloud run deploy asb-ml-app \
      --image asia-southeast1-docker.pkg.dev/ecgcga/app-repo/asb-ml-app:3f3c1fa \
      --region asia-southeast1 \
      --platform managed \
      --allow-unauthenticated \
      --memory 2Gi \
      --cpu 2 \
      --timeout 600 \
      --concurrency 5 \
      --set-env-vars GEMINI_API_KEY=$$GEMINI_API_KEY # <-- This is the deployment target for the secret
  env: # <--- THIS IS THE CRITICAL SECTION FOR THIS ERROR
  - 'GEMINI_API_KEY=${_GEMINI_API_KEY}' # This line explicitly maps the internally available secret
                                        # (from availableSecrets) to an environment variable
                                        # named GEMINI_API_KEY for *this specific step*.

# This section correctly declares which secret to fetch from Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/ecgcga/secrets/gemini-api-key/versions/latest
    env: '_GEMINI_API_KEY' # This makes the secret's value available internally as '_GEMINI_API_KEY'

# Optional: automatically set environment variables or secrets (uncomment if needed)
#   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#     entrypoint: gcloud
#     args:
#       [
#         "run",
#         "services",
#         "update",
#         "${_SERVICE_NAME}",
#         "--region",
#         "${_AR_REGION}",
#         "--update-env-vars",
#         "GEMINI_API_KEY=YOUR_API_KEY_HERE"
#       ]

#   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#     entrypoint: gcloud
#     args:
#       [
#         "run",
#         "services",
#         "update",
#         "${_SERVICE_NAME}",
#         "--region",
#         "${_AR_REGION}",
#         "--update-secrets",
#         "GEMINI_API_KEY=gemini_api_key:latest"
#       ]

# Fixes “invalid build: must specify logs bucket or logging option”
options:
  logging: CLOUD_LOGGING_ONLY

# Control build timeout (up to 1h by default)
timeout: 1200s
